### PR TITLE
cleanup and some builder bug fixes

### PR DESCRIPTION
**Pull request by aram10**

### CODE REVIEW

**Review by StarsMmd — COMMENTED** [review]
@aram10 it looks like there are a lot of indentation changes. Most likely it'd go back and forth between different people's settings so we should probably stick to one convention. Do you know if your settings are using tabs or spaces and how many?

**Comment by aram10** [comment]
My IDE automatically uses PEP 8 style guide rules - I can revert those if
you want

**Comment by aram10** [comment]
4 spaces per indentation level

**Comment by StarsMmd** [comment]
> My IDE automatically uses PEP 8 style guide rules - I can revert those if you want
> […](#)

Yeah let's revert the indentation stuff so it's easier to track the actual changes. If we decide to change the indentation conventions we can make a separate PR for that

**Pull request closed without merging**
